name: Build and deploy JAR app to Azure Web App - bookingsystem

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Print workspace contents
        run: ls -R ${{ github.workspace }}

      - name: List artifact contents
        run: ls -R ${{ github.workspace }}/target

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bookingsystem'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_427038C5938743F2BD6ED5F88F9C2261 }}
          package: '${{ github.workspace }}/target/*.jar'

      - name: Set deployment output variable
        id: set-deployment-output
        run: echo "webapp-url=${{ steps.deploy-to-webapp.outputs.webapp-url }}" >> $GITHUB_ENV

# This ensures the webapp-url is available as an output for subsequent steps or jobs
outputs:
  webapp-url: ${{ steps.set-deployment-output.outputs.webapp-url }}
